### ISSUE TITLE
'os/log.h' file not found when building for target x86_64-linux-android

### ISSUE THREAD

**Issue by patmuk** [steven-joruk/oslog#4]
On my Mac with OS 14.2.1 when building my flutter project, which includes a rust lib via Flutter-Rust-Bridge, for an Android emulator, I get the following error. For an iOS emulator  it works.

`SEVERE:   error occurred: Command "/Users/patmuk/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang" "-O0" "-DANDROID" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-2" "-fno-omit-frame-pointer" "--target=x86_64-linux-android" "--target=x86_64-linux-android21" "-o" "/Users/patmuk/code/own/sherry/system/sherry/shell_flutter/build/rust_builder/build/x86_64-linux-android/debug/build/oslog-5ee825ae84fb442f/out/wrapper.o" "-c" "wrapper.c" with args "clang" did not execute successfully (status code exit status: 1).`

`cargo:warning=wrapper.c:1:10: fatal error: 'os/log.h' file not found
SEVERE: 
SEVERE:   cargo:warning=#include <os/log.h>`

Probably a simpler setup compiling against "--target=x86_64-linux-android" "--target=x86_64-linux-android21" has the same issue.

Maybe adding `os/log.h` would solve it?

**Comment by simlay** [comment]
`oslog` is for the apple unified logging system.

I'm not sure what the cargo dependency you have setup is but you may want something like:
```toml
[target.'cfg(any(target_os = "ios", target_os = "macos"))'.dependencies]
oslog = "0.2.0"
```
This will make it so you're not building the `oslog` dependency for any android targets.

**Comment by patmuk** [comment]
Ah, many thanks! I should have read literally the first sentence of the readme :P
I am using rust in a Flutter project, compiling for iOS and Android.
Many thanks for the tip!
